version: "2"
services:
  portal:
    build: ./services/portal
    volumes:
      - ./services:/services
    ports:
      - "80:80"
    depends_on:
      - mongo
    links:
      - mongo
  cron:
    build: ./services/cron
    volumes:
      - ./services:/services
    depends_on:
      - mongo
    links:
      - mongo
  watcher:
    build: ./services/watcher
    volumes:
      - ./services:/services
    depends_on:
      - mongo
      - rabbit
    links:
      - mongo
      - rabbit
  gatekeeper:
    build: ./services/gatekeeper
    volumes:
      - ./services:/services
    depends_on:
      - mongo
      - rabbit
    links:
      - mongo
      - rabbit
  funnel:
    build: ./services/funnel
    volumes:
      - ./services:/services
    depends_on:
      - mongo
      - rabbit
    links:
      - mongo
      - rabbit
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: monitor
      MONGO_INITDB_ROOT_PASSWORD: m0n1t0r
      MONGO_INITDB_DATABASE: monitor
    ports:
      - "27017:27017"
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
